logger:
  encoder: console
  level: info
proxy:
  proxyHostA: http://localhost:5001
  proxyHostB: http://localhost:5000
  maxProcessTimeForUnavailable: 1s
  defaultEndpointTimeout: 60s
  wintr/connectors/storage/v3:
    url: redis://default:redis-password@localhost:6379
  httpServer:
    port: 5002
    certPath: .testdata/localhost.crt
    keyPath: .testdata/localhost.key